# Import the Pytorch library

In [ ]:
import torch
print(f"Pytorch version: {torch.__version__}") # Check the version

Pytorch version: 2.2.2


# Create Tensors

## 1. Create a tensor directly from data (e.g., a Python list)

In [ ]:
data = [[1, 2, 3], [4, 5, 6]]
x_data = torch.tensor(data)
print(f"Tensor created from Python list:\n{x_data}")

Tensor created from Python list:
tensor([[1, 2, 3],
        [4, 5, 6]])



## 2. Create a tensor of all zeros

In [ ]:
# Specify the shape of the tensor
shape = (2, 3)
zeros_tensor = torch.zeros(shape)
print(f"Tensor of zeros with shape {shape}:\n{zeros_tensor}")

Tensor of zeros with shape (2, 3):
tensor([[0., 0., 0.],
        [0., 0., 0.]])



## 3. Create a tensor of all ones

In [ ]:
ones_tensor = torch.ones(shape)
print(f"Tensor of ones with shape {shape}:\n{ones_tensor}")

Tensor of ones with shape (2, 3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])



## 4. Create a tensor with random values

In [ ]:
rand_tensor = torch.rand(shape)
print(f"Tensor of random values with shape {shape}:\n{rand_tensor}")

Tensor of random values with shape (2, 3):
tensor([[0.5343, 0.2521, 0.6053],
        [0.9454, 0.9638, 0.3365]])



# Tensor Attributes

In [7]:
# Let's inspect the attributes of the random tensor we created
print("--- Attributes of the random tensor ---")
print(f"Shape: {rand_tensor.shape}") # The dimensions of the tensor
print(f"Datatype: {rand_tensor.dtype}") # The type of data stored
print(f"Device: {rand_tensor.device}") # The device on which the tensor is stored

--- Attributes of the random tensor ---
Shape: torch.Size([2, 3])
Datatype: torch.float32
Device: cpu


In [ ]:
# You can explicitly create tensors with a specific datatype
float32_tensor = torch.ones(2, 2, dtype=torch.float32)
int64_tensor = torch.ones(2, 2, dtype=torch.int64)
print(f"Tensor with dtype float32:\n{float32_tensor}")
print(f"Tensor's dtype: {float32_tensor.dtype}\n")
print(f"Tensor with dtype int64:\n{int64_tensor}")
print(f"Tensor's dtype: {int64_tensor.dtype}")

Tensor with dtype float32:
tensor([[1., 1.],
        [1., 1.]])
Tensor's dtype: torch.float32

Tensor with dtype int64:
tensor([[1, 1],
        [1, 1]])
Tensor's dtype: torch.int64

