In [ ]:
import torch

# Let's create a sample tensor to work with

In [2]:
# A 3x4 tensor
tensor = torch.tensor([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])
print(f"Original Tensor:\n{tensor}")

Original Tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


# 1. Indexing and Slicing

In [3]:
# Access the first row
first_row = tensor[0]
print(f"First Row:{first_row}")

First Row:tensor([1, 2, 3, 4])


In [4]:
# Access the first column
first_col = tensor[:, 0]
print(f"First Column:{first_col}")

First Column:tensor([1, 5, 9])


In [5]:
# Access a specific element
element = tensor[1, 2]
print(f"Element at [1, 2]: {element}")
print(f"Value of the element: {element.item()}") # .item() gets the Python number value from a single-element tensor

Element at [1, 2]: 7
Value of the element: 7


In [6]:
# Get the first two rows
first_two_rows = tensor[0:2] # or tensor[:2]
print(f"First two rows:\n{first_two_rows}")

First two rows:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [7]:
# Get the last two columns
last_two_cols = tensor[:, 2:4] # or tensor[:, -2:]
print(f"Last two columns:\n{last_two_cols}")

Last two columns:
tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]])


In [8]:
# Get a subgrid
subgrid = tensor[1:3, 1:3]
print(f"Subgrid (rows 1-2, cols 1-2):\n{subgrid}")

Subgrid (rows 1-2, cols 1-2):
tensor([[ 6,  7],
        [10, 11]])


# 2. Basic Arithmetic Operations

In [9]:
# Create another tensor for operations
tensor_b = torch.ones(3, 4) * 3 # A 3x4 tensor filled with 3s
print(f"Tensor A:\n{tensor}")
print(f"Tensor B:\n{tensor_b}")

Tensor A:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Tensor B:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [10]:
# Addition
sum_tensor = tensor + tensor_b
# Alternative syntax: sum_tensor = torch.add(tensor, tensor_b)
print(f"Addition (A + B):\n{sum_tensor}")

Addition (A + B):
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


In [11]:
# Subtraction
diff_tensor = tensor - tensor_b
# Alternative syntax: diff_tensor = torch.sub(tensor, tensor_b)
print(f"Subtraction (A - B):\n{diff_tensor}")

Subtraction (A - B):
tensor([[-2., -1.,  0.,  1.],
        [ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.]])


In [12]:
# Element-wise Multiplication (Hadamard product)
mult_tensor = tensor * tensor_b
# Alternative syntax: mult_tensor = torch.mul(tensor, tensor_b)
print(f"Element-wise Multiplication (A * B):\n{mult_tensor}")

Element-wise Multiplication (A * B):
tensor([[ 3.,  6.,  9., 12.],
        [15., 18., 21., 24.],
        [27., 30., 33., 36.]])


In [13]:
# Element-wise Division
div_tensor = tensor / tensor_b
# Alternative syntax: div_tensor = torch.div(tensor, tensor_b)
print(f"Element-wise Division (A / B):\n{div_tensor}")

Element-wise Division (A / B):
tensor([[0.3333, 0.6667, 1.0000, 1.3333],
        [1.6667, 2.0000, 2.3333, 2.6667],
        [3.0000, 3.3333, 3.6667, 4.0000]])


In [14]:
# --- In-place Operations ---
# Operations ending with _ modify the tensor directly
print(f"Original Tensor A before in-place add:\n{tensor}")
tensor.add_(tensor_b.int()) # Adds tensor_b to tensor *in-place*
print(f"Tensor A after in-place add:\n{tensor}")
# Reset tensor A for next example
tensor = torch.tensor([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])

Original Tensor A before in-place add:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Tensor A after in-place add:
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [15]:
# --- Broadcasting ---
# PyTorch can automatically expand the dimensions for operations if sizes are compatible
scalar = 10
# Add a scalar to the tensor - scalar is "broadcase" to match tensor shape
add_scalar = tensor + scalar
print(f"Add scalar ({scalar}) to tensor:\n{add_scalar}")

Add scalar (10) to tensor:
tensor([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]])


In [16]:
row_vector = torch.tensor([10, 20, 30, 40]) # A 1x4 tensor
# Add row vector to each row of the tensor - vector is broadcast across rows
add_vector = tensor + row_vector
print(f"Add row vector {row_vector} to tensor:\n{add_vector}")

Add row vector tensor([10, 20, 30, 40]) to tensor:
tensor([[11, 22, 33, 44],
        [15, 26, 37, 48],
        [19, 30, 41, 52]])
