In [2]:
import torch

# Sample Tensors

In [3]:
# A tensor with 12 elements
tensor_a = torch.arange(1, 13) # Creates a 1D tensor: [1, 2, ..., 12]
print(f"Original Tensor A (1D):\n{tensor_a}\nShape: {tensor_a.shape}")

Original Tensor A (1D):
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Shape: torch.Size([12])


# 1. Reshaping Tensors

In [4]:

# Use reshape() or view() to change dimensions. Total elements must remain the same.

# Reshape to 3 rows, 4 columns
tensor_reshaped = tensor_a.reshape(3, 4)
# Alternative: tensor_reshaped = tensor_a.view(3, 4)
# view() creates a view sharing the same underlying data, reshape() might return a view or a copy.
# reshape() is generally more flexible.
print(f"Tensor A reshaped to (3, 4):\n{tensor_reshaped}\nShape: {tensor_reshaped.shape}")

Tensor A reshaped to (3, 4):
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Shape: torch.Size([3, 4])


In [5]:
# Flatten a multi-dimensional tensor back to 1D
# Use -1 to let PyTorch infer the dimension size
tensor_flat = tensor_reshaped.reshape(-1)
print(f"Tensor reshaped back to flat (1D):\n{tensor_flat}\nShape: {tensor_flat.shape}")

Tensor reshaped back to flat (1D):
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Shape: torch.Size([12])


# 2. Matrix Multiplication

In [ ]:
# Requires compatible shapes: (m x n) @ (n x p) results in (m x p)
tensor_m1 = tensor_reshaped.float() # Matmul often expects float types
print(f"Matrix 1 (3x4):\n{tensor_m1}")

Matrix 1 (3x4):
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [7]:
# Create a compatible matrix (4 rows, 2 columns)
tensor_m2 = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=torch.float32)
print(f"Matrix 2 (4x2):\n{tensor_m2}")

Matrix 2 (4x2):
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
# Perform matrix multiplication using '@' operator
matmul_result = tensor_m1 @ tensor_m2
# Alternative syntax: matmul_result = torch.matmul(tensor_m1, tensor_m2)
print(f"Matrix Multiplication Result (3x2):\n{matmul_result}\nShape: {matmul_result.shape}")
#!!! Contrast with element-wise multiplication (*) which requires SAME shape !!!
#This would fail: tensor_m1 * tensor_m2 (shapes (3,4) and (4,2) are different)
#If tensor_m1 and tensor_m2 had the *same* shape, '*' would multiply element-by-element.

Matrix Multiplication Result (3x2):
tensor([[ 50.,  60.],
        [114., 140.],
        [178., 220.]])
Shape: torch.Size([3, 2])


# 3. Aggregation Operations

In [9]:
# Use our (3, 4) reshaped tensor again
print(f"Tensor for aggregation:\n{tensor_reshaped}")

Tensor for aggregation:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [10]:
# Sum of all elements
total_sum = torch.sum(tensor_reshaped)
# Alternative: total_sum = tensor_reshaped.sum()
print(f"Sum of all elements: {total_sum.item()}") # .item() extracts the single value

Sum of all elements: 78


In [11]:
# Mean of all elements (requires float type)
total_mean = torch.mean(tensor_reshaped.float())
# Alternative: total_mean = tensor_reshaped.float().mean()
print(f"Mean of all elements: {total_mean.item()}")

Mean of all elements: 6.5


In [12]:
# Sum along a specific dimension (dim)
# Sum along columns (sum each column, collapse rows -> dim=0)
sum_cols = torch.sum(tensor_reshaped, dim=0)
print(f"Sum along columns (dim=0): {sum_cols}\nShape: {sum_cols.shape}")

Sum along columns (dim=0): tensor([15, 18, 21, 24])
Shape: torch.Size([4])


In [13]:
# Sum along rows (sum each row, collapse columns -> dim=1)
sum_rows = torch.sum(tensor_reshaped, dim=1)
print(f"Sum along rows (dim=1): {sum_rows}\nShape: {sum_rows.shape}")

Sum along rows (dim=1): tensor([10, 26, 42])
Shape: torch.Size([3])


In [15]:
# Max value and its index
max_val, max_idx = torch.max(tensor_reshaped, dim=1) # Find max in each row (along dim=1)
print(f"Max value in each row: {max_val}")
print(f"Index of max value in each row: {max_idx}")

Max value in each row: tensor([ 4,  8, 12])
Index of max value in each row: tensor([3, 3, 3])


In [16]:
# Min value
min_val = torch.min(tensor_reshaped) # Overall minimum
print(f"Minimum value in tensor: {min_val.item()}")

Minimum value in tensor: 1
