In [1]:
import torch
import numpy as np

# 1. NumPy Bridge

In [2]:
# Create a PyTorch Tensor (on CPU by default)
tensor_cpu = torch.ones(5)
print(f"PyTorch Tensor: {tensor_cpu}")

PyTorch Tensor: tensor([1., 1., 1., 1., 1.])


In [3]:
# Convert Tensor to NumPy array
# NOTE: The tensor and NumPy array will share the same memory location (on CPU),
# so changing one will change the other!
numpy_array = tensor_cpu.numpy()
print(f"Converted NumPy Array: {numpy_array}")

Converted NumPy Array: [1. 1. 1. 1. 1.]


In [4]:
# Modify the tensor in-place and see NumPy array change
tensor_cpu.add_(1)
print(f"Tensor after modification: {tensor_cpu}")
print(f"Numpy array after tensor modification: {numpy_array}")

Tensor after modification: tensor([2., 2., 2., 2., 2.])
Numpy array after tensor modification: [2. 2. 2. 2. 2.]


In [5]:
# Create a NumPy array
numpy_array_b = np.array([10, 20, 30, 40, 50])
print(f"NumPy Array B: {numpy_array_b}")

NumPy Array B: [10 20 30 40 50]


In [6]:
# Convert NumPy array to PyTorch Tensor
tensor_from_numpy = torch.from_numpy(numpy_array_b)
print(f"Converted PyTorch Tensor: {tensor_from_numpy}")

Converted PyTorch Tensor: tensor([10, 20, 30, 40, 50])


In [7]:
# Modify the NumPy array and see the tensor change
np.add(numpy_array_b, 1, out=numpy_array_b)
print(f"NumPy array after modification: {numpy_array_b}")
print(f"Tensor after NumPy array modification: {tensor_from_numpy}")

NumPy array after modification: [11 21 31 41 51]
Tensor after NumPy array modification: tensor([11, 21, 31, 41, 51])


# 2. Moving Tensors between CPU and GPU

In [8]:
if torch.cuda.is_available():
    device = torch.device("cuda") # Use GPU
    print(f"GPU ({torch.cuda.get_device_name(0)}) is available. Using device: {device}")
else:
    device = torch.device("cpu") # Use CPU
    print(f"GPU not available. Using device: {device}")

GPU not available. Using device: cpu


In [9]:
# Create a tensor (defaults to CPU)
tensor_on_cpu = torch.randn(3, 3)
print(f"Tensor initially on device: {tensor_on_cpu.device}")

Tensor initially on device: cpu


In [10]:
# Move the tensor to the selected device (GPU if available, else CPU)
tensor_on_device = tensor_on_cpu.to(device)
print(f"Tensor moved to device: {tensor_on_device.device}")

Tensor moved to device: cpu


In [11]:
# Perform some operation on the target device
# NOTE: All tensors involved in an operation must be on the SAME device!
tensor_b_on_device = torch.ones(3, 3, device=device) # Create tensor B directly on target device
result = tensor_on_device + tensor_b_on_device
print(f"Result of operation on {device}:\n{result}")
print(f"Result tensor is on device: {result.device}")

Result of operation on cpu:
tensor([[-0.8003,  1.0163,  0.7143],
        [ 1.5643,  1.5177, -0.2157],
        [-0.2157,  2.9878,  0.1184]])
Result tensor is on device: cpu


In [ ]:
# Move the result back to the CPU
# Important if you need to convert back to NumPy or use with CPU-only libraries
result_on_cpu = result.to("cpu")
# Alternative shorthand: result_on_cpu = result.cpu()
print(f"Result moved back to CPU device: {result_on_cpu.device}")

Result moved back to CPU device: cpu


In [14]:
# Try converting the GPU tensor directly to NumPy (will cause an error!)
# numpy_from_gpu = result.numpy() # This would raise an error if result is on GPU

# Convert the CPU tensor to NumPy (works fine)
numpy_from_cpu = result_on_cpu.numpy()
print(f"Result converted to NumPy (after moving to CPU):\n{numpy_from_cpu}")


Result converted to NumPy (after moving to CPU):
[[-0.80026245  1.0163411   0.71431994]
 [ 1.5642942   1.517679   -0.21572459]
 [-0.21572173  2.9878426   0.11840779]]
